[package]
name = "liserk-encrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tikv-client = "0.1.0"
tokio = { version = "1.28", features = ["full"] }
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "aarch64-unix"] }
